builds, but I broke a test badly
failures:

---- utils::tests::test_midi_routing stdout ----
thread 'utils::tests::test_midi_routing' panicked at 'Expected some sound because the arpeggiator is now running.', src/utils.rs:578:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace